version: '3.3'
services:
  db:
    image: postgres
    container_name: postgres_flask
    restart: always
    environment:
      - POSTGRES_DB=flaskdb
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - db_flask:/var/lib/postgresql/data/
    ports:
      - '54320:5432'

  web:
      build: .
      restart: always
      volumes:
        - web_static:/app/static/
      ports:
        - '127.0.0.1:5000:5000'
      depends_on:
        - db
      env_file:
        - ./.env

volumes:
  db_flask:
  web_static:
