version: "3.3"
services:
  db:
    image: postgres:13-alpine
    container_name: postgres_flask
    restart: always
    environment:
      - POSTGRES_DB=flaskdb
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=12345
    networks:
      - default
    volumes:
      - db_flask:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
      build: .
      command: flask run -h 0.0.0.0
      restart: always
      networks:
        - default
      volumes:
        - web_static:/app/static/
      ports:
        - "5000:5000"
      depends_on:
        - db
      env_file:
        - ./.env

volumes:
  db_flask:
  web_static:
